#%RAML 0.8
title: ChewCrew
version: v1
baseUri: http://chewcrew.io/

/sessions:
  post:
    description: Create a voting session. Returns the session ID that voters will use to connect to the session.
  /{id}:
	post:
      description: Join a session. Returns the voter ID that each voter will use for future actions.
      queryParameters:
        name:
          description: Voter name
    put:
      description: Vote in a session
      queryParameters:
        voterid:
          description: Voter ID
        choiceid:
          description: Choice ID
    get:
      description: Retrieve a voting session. If the session is Started, then choices will be populated. If the session is Ended (either by everyone voting or forcefully ended by the host), then the vote count for each choice will be populated.
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                "$schema": "http://json-schema.org/schema",
                "type": "object",
                "description": "A voting session",
                "properties": {
                "voters": "Participating voters",
                "voters": {
                  "type": "array",
                  "name": {"type": "string"}
                  },
                "choices": "Voting choices. Will be populated when the voting session has started. Vote counts will be populated once votes are tallied.",
                "choices": {
                  "type": "array",
                  "items": {"type" : "string"},
                  "minItems": 5,
                  "uniqueItems": true
                  }
                }}
	/start:
      post:
        description: Starts the voting session. Only the session host is authorized to start the vote.
        queryParameters:
          voterid:
            description: Voter ID to identify the session host
    /end:
      post:
        description: Forcefully ends a voting session to tally existing votes. Only the session host is authorized.
        queryParameters:
          voterid:
            description: Voter ID to identify the session host
